### PR TITLE
Support `drive_link` query parameter

### LINKED ISSUE #12: Link with ?usp=drive_link is considered as invalid
Hi,

I have a link - https://drive.google.com/file/d/1MDYfFf4a-pJOst1Qos2ufdcZZB5OiRtg/view?usp=drive_link
parsing it gives an error: Invalid URL provided
the link is a valid one though

### PR DESCRIPTION
**Pull request by vladshcherbin**
Resolve #12

### CODE REVIEW

**Comment by Richienb** [comment]
I wonder, would it be better to remove the query param part entirely?

**Comment by Richienb** [comment]
Nevermind, this is addressed in #11

**Comment by vladshcherbin** [comment]
@Richienb perfect, thank you! Any change to roll a release any time soon?

**Comment by Richienb** [comment]
> Any change to roll a release any time soon?

[`v2.0.1`](https://github.com/Richienb/drive-url/releases/tag/v2.0.1) real

**Comment by vladshcherbin** [comment]
@Richienb perfect, big thank you! 🤗

**Pull request merged**
